# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Bio.create(name: 'James E. Besser', description: 'James E. Besser is co-portfolio manager of the Partnership. Since July 1999, he has been the portfolio manager of JEB Partners and a managing member of the General Partner.  From August 1998 to April 1999, he worked as an analyst at Highflelds Capital, a Boston based hedge Partnership. Mr. Besser was an analyst at Media Group Research from June 1997 to June 1998. Media Group Research is a Media, Communications, and Entertainment research boutique that also operates a hedge fund.  Mr. Besser was a seasonal employee of Manchester Management for 8 years, from 1989 to 1996.  Mr. Besser has visited and performed due diligence on numerous companies, met hundreds of managements and read thousands of company filings and offering documents in his years in the investment business.  He believes that his greatest strengths are in the evaluation of managements and evaluating disparate types of information to foresee trends in industries.  Mr. Besser graduated from Brown University in Providence, Rhode Island, in June 1997 with a Bachelor of Arts degree.')
Bio.create(name: 'Morgan C. Frank', description: 'Morgan C. Frank is a consultant to Manchester Management and co-portfolio manager of the Partnership.  He has worked as a consultant to Manchester Management since May 2002.  Prior to that, he was a founder and managing director at First Principles Group (groupfp.com), a boutique consultancy and principal investor specializing in corporate restructuring, restarts, intellectual property assessment and salvage, and spin outs.  From September 1996 to May 2001, Mr. Frank spent 5 years as an analyst and portfolio manager at Hollis Capital, a San Francisco hedge fund manager specializing in technology, life sciences, finance, and energy.  Before this, he worked for an independent private client group at Paine Webber specializing in performing primary research to develop investment ideas (particularly short sale ideas) for institutional clients, and prior to that, Mr. Frank was a currency trader for Eastern Vanguard.  He holds a BA in Economics and Political Science from Brown University.')
Bio.create(name: 'Donald E. Besser', description: 'Donald E. Besser is the co-manager of the General Partner, which he founded in 1987.  From 1971 to 1987 Mr. Besser operated independently as a private investor and trader.  From 1985 to early 1987, he was also a research consultant to Homans, McGraw, Trull, Valeo and Company.  Mr. Besser worked for Fred Alger & Co. from 1969 to 1971.  Since 1991, Mr. Besser has focused almost exclusively on short selling.  Mr. Besser holds a Bachelor of Arts degree from Brown University and a Masters of Business Administration from the Sloan School, Massachusetts Institute of Technology.')
